name: Update Video Gallery
on:
  schedule:
    - cron: '*/30 * * * *' # Cek video baru tiap 30 menit
  workflow_dispatch: # Tombol rahasia untuk jalankan manual

jobs:
  update-gallery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Ambil Video dari Telegram
        run: |
          curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/getUpdates" > data_telegram.json
          echo "Data berhasil diambil."

      - name: Simpan Data ke GitHub
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data_telegram.json
          git commit -m "Update video otomatis" || exit 0
          git push
          
